### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by vitr** [Laravel-Backpack/NewsCRUD#1]
Where is the code for the tests? So far,  I've seen only phpunit command as composer test, but there is no phpunit.xml or anything related. Am I missing something?

**Comment by tabacitu** [comment]
Unfortunately, you are not missing anything. The packages have no unit tests right now - that's pretty much the only thing keeping Backpack from going out of public beta. 

If you'd like to contribute with unit tests, I would be very happy to help in any way I can, but please coordinate with me, since other people have expressed interest in writing them and we wouldn't want two people to work on the same tests.

Thanks!

**Comment by vitr** [comment]
well, yeah, I'd like to participate. you sound very reasonable, If you have any guidelines, roadmaps, etc., I'm happy to follow.

**Comment by tabacitu** [comment]
Great to hear that! I do have a long-term product roadmap, but I think that will more likely confuse, rather than help, because it's not well explained. 

For short and medium-term, we should use github issues to plan our work. All Backpack packages need unit testing, so far a few people have expressed interest and none have actually done it :-) So you're free to start wherever you want, for now.

Here's the procedure we've settled upon so 2 people don't work on the same thing:
- you find something that needs doing (say: unit tests for a certain package);
- you check if there is already an issue for it; if not, add one;
- in that issue, say you're working on it and it will be done in x hours or y days, assign the "working on it" label and/or assign yourself to the issue; any form that will let other people know you're on it; 
- then comment/close/reference the issue in your pull request;

That way, no overlapping. How does that sound?

**Comment by vitr** [comment]
sorry, for the delay, sounds good, I'm opening the issue then

**Comment by tabacitu** [comment]
Hmm... yeah, apparently only organisation members can do that. I've labeled it for you, which also automatically moves it in the right column in our [waffle](https://waffle.io/Laravel-Backpack/crud).

Cheers!
