### ISSUE TITLE
Slug on tag and category are wrong saved

### ISSUE THREAD

**Issue by lejubila** [Laravel-Backpack/NewsCRUD#18]
Hallo,
in the category and tags modules, when I insert in the field slug a similar value to this "category/travel" is saved incorrectly. The stored value is "travel" instead of "category/travel".
In the article module instead the value is saved correctly.
Can you help me solve this problem?

Thank you.

**Comment by OwenMelbz** [comment]
Hi @lejubila 

If I understand correctly, you're saying if you enter something like "category/travel" the slug that gets generated removes the `/` ???

If so - this is because slugs are URL compatible. Having a `/` in the slug would potentially cause conflicts with other routes as its a 2 segment url. So this is the expected behavior (unless i misunderstood your question)

**Comment by tabacitu** [comment]
I understand it differently - that @lejubila wants to store the slug as "category/travel", "category/announcements" for each category. 

My opinion is that it's a better to save "travel" in the database, not "category/travel", because if you decide to rename "category" to something else, you can do that without modifying anything in the database.

But if you do decide to save it like that, I think you can use an [Eloquent Mutator](https://laravel.com/docs/5.3/eloquent-mutators#defining-a-mutator) and append the "category/" prefix to all slugs, when you save them in the database.

Hope it helps. Cheers!

**Comment by lejubila** [comment]
@tabacitu,
you understood well.
What I do not understand is that in the article module the slug can save a value of type "segment/segment" instead in tag and category no.
Analyzing the source code of several unknown classes significant differences that can justify this behavior.

**Comment by tabacitu** [comment]
Hi @lejubila ,

I'm afraid I didn't understand this: "_What I do not understand is that in the article module the slug can save a value of type "segment/segment" instead in tag and category no. Analyzing the source code of several unknown classes significant differences that can justify this behavior._"

Could you please rephrase?

Cheers!

**Comment by tabacitu** [comment]
PS. I closed the issue, as I'm pretty sure it's not a bug. If it turns out to be a new feature, I'll reopen it. We can continue the talk here, in the meantime.
