### ISSUE TITLE
Article Status won't get updated

### ISSUE THREAD

**Issue by dahdash** [Laravel-Backpack/NewsCRUD#63]
# Bug report
If Article Status changes to 'DRAFT', it won't get updated.

### What happened:
The Status field in form pass 0 and 1 to enum entity and it always update the field to default value for enum (PUBLISHED).

### What I've already tried to fix it:
Change Status field type from select_from_array to enum would solve the issue:
            $this->crud->addField([
                'name' => 'status',
                'label' => 'Status',
                'type' => 'enum',
            ]);

### Backpack, Laravel, PHP, DB version:
Backpack 5.0.18, Laravel 9.13, PHP 8.1.6, mysql  Ver 15.1 Distrib 10.7.3-MariaDB

**Comment by tabacitu** [comment]
Good catch @dahdash - thanks for taking the time to see WHY this doesn't work, and explain it. 

Changing the field to `enum` works, yes, but we wanted to use `select_from_array` here so that it also works on non-MySQL databases. So I've changed the options of `select_from_array` instead. After https://github.com/Laravel-Backpack/NewsCRUD/pull/64 it should all work fine - please let us know if it doesn't.

Thanks again.
Cheers!
